### ISSUE TITLE
Conflict with TweetDeck

### ISSUE THREAD

**Issue by Seriousseriesfanatic** [dangeredwolf/Twitter-Web-Enhancer#2]
Conflicting resources being used, probably due to the URL Twitter Web Enhancer runs on and that Tweetdeck runs on 
Before disabling the plugin:
![ss 2015-03-19 at 10 20 48](https://cloud.githubusercontent.com/assets/11559930/6736796/458fea3a-ce24-11e4-874f-02bca242ac1e.jpg)
And after: 
![ss 2015-03-19 at 10 28 23](https://cloud.githubusercontent.com/assets/11559930/6736815/6506af66-ce24-11e4-9101-74bf25bb92f3.jpg)
(Columns grayed out intentionally)

**Comment by dangeredwolf** [comment]
Download the latest Twitter Web Enhancer, it fixes it
